FROM debian
LABEL maintener 'Maycon Carlete'

ARG S3_BUCKET=files
ENV S3_BUCKET=${S3_BUCKET}

#Para adicionar na linha de comando parametro
#docker image build --build-arg S3_BUCKET=myapp -t segundo-build . (coloque o ponto diretorio)

